"""add idx_status_created to tasks

Revision ID: 058325e8430a
Revises: 48bb696ca637
Create Date: 2026-08-30 00:10:32.370709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058325e8430a'
down_revision: Union[str, Sequence[str], None] = '48bb696ca637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_status_created', 'tasks', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_created', table_name='tasks')
    # ### end Alembic commands ###
